### PR TITLE
Create single product page

### PR DESCRIPTION
**Pull request by Victorywastaken**

### CODE REVIEW

**Review by bsullit — COMMENTED** [review]
*fixed* conflicts

**Review by bsullit — CHANGES_REQUESTED** [review]
finish hooking up redux

**Comment by Victorywastaken** [comment]
reworked single product page, connected both front and back end, should be able to get single component views now. Please approve.

**Review by trzaidi — APPROVED** [review]
cool beans

**Review by bsullit — APPROVED** [review]
fixed merge issues

**Pull request merged**
